definitions:
  letterboxd.Pagination:
    properties:
      current_page:
        type: integer
      is_last:
        type: boolean
      next_page:
        type: integer
      total_pages:
        type: integer
    type: object
  v1.APIResponse:
    properties:
      data: {}
      pagination:
        $ref: '#/definitions/letterboxd.Pagination'
    type: object
info:
  contact: {}
paths:
  /films/{slug}:
    get:
      consumes:
      - application/json
      description: Get a film from a film slug
      parameters:
      - description: Film slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.APIResponse'
      summary: Get List Example
      tags:
      - films
  /lists/{user}/{slug}:
    get:
      consumes:
      - application/json
      description: Get a list of films from a user's list
      parameters:
      - description: Username of the list owner
        in: path
        name: user
        required: true
        type: string
      - description: List slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.APIResponse'
      summary: Get List Example
      tags:
      - list
  /users/{user}/watched:
    get:
      consumes:
      - application/json
      description: Get watched fils of a user
      parameters:
      - description: user
        in: path
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.APIResponse'
      summary: Get watched films per user
      tags:
      - users
swagger: "2.0"
